Update test.patch

diff --git a/test.patch b/test.patch
--- a/test.patch
+++ b/test.patch
@@ -25,7 +25,7 @@ index 3f2706e28f..63f602a1b6 100644
      },
      "extra": {
 diff --git a/composer.lock b/composer.lock
-index bb5244b40b..f083450f58 100644
+index 5b6777f9a7..f0eca63736 100644
 --- a/composer.lock
 +++ b/composer.lock
 @@ -4,7 +4,7 @@
@@ -37,7 +37,7 @@ index bb5244b40b..f083450f58 100644
      "packages": [
          {
              "name": "asm89/stack-cors",
-@@ -5319,6 +5319,107 @@
+@@ -5318,6 +5318,107 @@
              },
              "time": "2021-07-22T09:24:00+00:00"
          },
@@ -145,7 +145,7 @@ index bb5244b40b..f083450f58 100644
          {
              "name": "mikey179/vfsstream",
              "version": "v1.6.10",
-@@ -5428,6 +5529,158 @@
+@@ -5427,6 +5528,158 @@
              ],
              "time": "2020-11-13T09:40:50+00:00"
          },
@@ -304,7 +304,7 @@ index bb5244b40b..f083450f58 100644
          {
              "name": "nikic/php-parser",
              "version": "v4.13.2",
-@@ -5874,6 +6127,115 @@
+@@ -5873,6 +6126,115 @@
              },
              "time": "2020-07-09T08:33:42+00:00"
          },
@@ -420,7 +420,7 @@ index bb5244b40b..f083450f58 100644
          {
              "name": "phpunit/php-code-coverage",
              "version": "9.2.10",
-@@ -8077,6 +8439,50 @@
+@@ -8076,6 +8438,50 @@
              ],
              "time": "2021-07-28T10:34:58+00:00"
          },
@@ -601,145 +601,6 @@ index 413272eff3..6cd43fd966 100644
 +#      # Run nightwatch testing.
 +#      # @see https://www.drupal.org/project/drupal/issues/2869825
 +#      nightwatchjs: {}
-diff --git a/core/lib/Drupal/Core/Database/Statement.php b/core/lib/Drupal/Core/Database/Statement.php
-index fb9a1b8eb6..c53a64f1f9 100644
---- a/core/lib/Drupal/Core/Database/Statement.php
-+++ b/core/lib/Drupal/Core/Database/Statement.php
-@@ -21,7 +21,7 @@
-  *
-  * @see https://www.drupal.org/node/3177488
-  */
--class Statement extends \PDOStatement implements StatementInterface {
-+class Statement extends \PDOStatement {
- 
-   /**
-    * Reference to the database connection object for this statement.
-@@ -54,6 +54,7 @@ public function getConnectionTarget(): string {
-   /**
-    * {@inheritdoc}
-    */
-+  #[\ReturnTypeWillChange]
-   public function execute($args = [], $options = []) {
-     if (isset($options['fetch'])) {
-       if (is_string($options['fetch'])) {
-@@ -148,6 +149,7 @@ public function fetchAssoc() {
-   /**
-    * {@inheritdoc}
-    */
-+  #[\ReturnTypeWillChange]
-   public function rowCount() {
-     // SELECT query should not use the method.
-     if ($this->allowRowCount) {
-@@ -161,7 +163,7 @@ public function rowCount() {
-   /**
-    * {@inheritdoc}
-    */
--  public function setFetchMode($mode, $a1 = NULL, $a2 = []) {
-+  public function setFetchMode(int $mode, mixed ...$args) {
-     // Call \PDOStatement::setFetchMode to set fetch mode.
-     // \PDOStatement is picky about the number of arguments in some cases so we
-     // need to be pass the exact number of arguments we where given.
-@@ -170,18 +172,19 @@ public function setFetchMode($mode, $a1 = NULL, $a2 = []) {
-         return parent::setFetchMode($mode);
- 
-       case 2:
--        return parent::setFetchMode($mode, $a1);
-+        return parent::setFetchMode($mode, $args[0]);
- 
-       case 3:
-       default:
--        return parent::setFetchMode($mode, $a1, $a2);
-+        return parent::setFetchMode($mode, $args[0], $args[1] ?? []);
-     }
-   }
- 
-   /**
-    * {@inheritdoc}
-    */
--  public function fetchAll($mode = NULL, $column_index = NULL, $constructor_arguments = NULL) {
-+  #[\ReturnTypeWillChange]
-+  public function fetchAll(int $mode = \PDO::FETCH_DEFAULT, mixed ...$args) {
-     // Call \PDOStatement::fetchAll to fetch all rows.
-     // \PDOStatement is picky about the number of arguments in some cases so we
-     // need to be pass the exact number of arguments we where given.
-@@ -193,11 +196,11 @@ public function fetchAll($mode = NULL, $column_index = NULL, $constructor_argume
-         return parent::fetchAll($mode);
- 
-       case 2:
--        return parent::fetchAll($mode, $column_index);
-+        return parent::fetchAll($mode, $args[0]);
- 
-       case 3:
-       default:
--        return parent::fetchAll($mode, $column_index, $constructor_arguments);
-+        return parent::fetchAll($mode, $args[0], $args[1]);
-     }
-   }
- 
-diff --git a/core/lib/Drupal/Core/Database/StatementEmpty.php b/core/lib/Drupal/Core/Database/StatementEmpty.php
-index fe173ecea3..2243200033 100644
---- a/core/lib/Drupal/Core/Database/StatementEmpty.php
-+++ b/core/lib/Drupal/Core/Database/StatementEmpty.php
-@@ -46,6 +46,7 @@ public function getQueryString() {
-   /**
-    * {@inheritdoc}
-    */
-+  #[\ReturnTypeWillChange]
-   public function rowCount() {
-     if ($this->allowRowCount) {
-       return 0;
-@@ -89,6 +90,7 @@ public function fetchAssoc() {
-   /**
-    * {@inheritdoc}
-    */
-+  #[\ReturnTypeWillChange]
-   public function fetchAll($mode = NULL, $column_index = NULL, $constructor_arguments = NULL) {
-     return [];
-   }
-@@ -131,6 +133,7 @@ public function key() {
-   /**
-    * {@inheritdoc}
-    */
-+  #[\ReturnTypeWillChange]
-   public function rewind() {
-     // Nothing to do: our DatabaseStatement can't be rewound.
-   }
-@@ -138,6 +141,7 @@ public function rewind() {
-   /**
-    * {@inheritdoc}
-    */
-+  #[\ReturnTypeWillChange]
-   public function next() {
-     // Do nothing, since this is an always-empty implementation.
-   }
-@@ -145,6 +149,7 @@ public function next() {
-   /**
-    * {@inheritdoc}
-    */
-+  #[\ReturnTypeWillChange]
-   public function valid() {
-     return FALSE;
-   }
-diff --git a/core/lib/Drupal/Core/Database/StatementWrapper.php b/core/lib/Drupal/Core/Database/StatementWrapper.php
-index 2b3eb40f46..39e0e3988f 100644
---- a/core/lib/Drupal/Core/Database/StatementWrapper.php
-+++ b/core/lib/Drupal/Core/Database/StatementWrapper.php
-@@ -352,6 +352,7 @@ public function bindColumn($column, &$param, int $type = 0, int $maxlen = 0, $dr
-         return $this->clientStatement->bindColumn($column, $param, $type, $maxlen);
- 
-       case 5:
-+      default:
-         return $this->clientStatement->bindColumn($column, $param, $type, $maxlen, $driverdata);
- 
-     }
-@@ -399,6 +400,7 @@ public function bindParam($parameter, &$variable, int $data_type = \PDO::PARAM_S
-         return $this->clientStatement->bindParam($parameter, $variable, $data_type, $length);
- 
-       case 5:
-+      default:
-         return $this->clientStatement->bindParam($parameter, $variable, $data_type, $length, $driver_options);
- 
-     }
 diff --git a/core/lib/Drupal/Core/File/MimeType/MimeTypeGuesser.php b/core/lib/Drupal/Core/File/MimeType/MimeTypeGuesser.php
 index d42f7ab901..90a2c4257e 100644
 --- a/core/lib/Drupal/Core/File/MimeType/MimeTypeGuesser.php
@@ -1987,7 +1848,7 @@ index 0000000000..72f826f639
 +    - "#^Class .* extends @internal class#"
 +    - "#^File .* could not be loaded from module_load_include.#"
 diff --git a/core/scripts/dev/commit-code-check.sh b/core/scripts/dev/commit-code-check.sh
-index e5cba55695..b7a99ce6ae 100755
+index e5cba55695..688c57d611 100755
 --- a/core/scripts/dev/commit-code-check.sh
 +++ b/core/scripts/dev/commit-code-check.sh
 @@ -11,6 +11,7 @@
@@ -1998,26 +1859,29 @@ index e5cba55695..b7a99ce6ae 100755
  # - ESLint checks JavaScript and YAML files.
  # - Checks .es6.js and .js files are equivalent.
  # - Stylelint checks CSS files.
-@@ -283,6 +284,19 @@
-     cd $TOP_LEVEL
-   fi
+@@ -181,6 +182,22 @@
+ printf -- '-%.0s' {1..100}
+ printf "\n"
  
-+  ############################################################################
-+  ### PHPSTAN
-+  ############################################################################
-+  if [[ -f "$TOP_LEVEL/$FILE" ]] && [[ $FILE =~ \.(inc|install|module|php|profile|test|theme)$ ]]; then
-+    vendor/bin/phpstan analyze --no-progress --configuration="$TOP_LEVEL/core/phpstan.neon.dist" "$TOP_LEVEL/$FILE"
-+    if [ "$?" -ne "0" ]; then
-+      # If there are failures set the status to a number other than 0.
-+      STATUS=1
-+    else
-+      printf "PHPStan: $FILE ${green}passed${reset}\n"
-+    fi
-+  fi
++# Run PHPStan on all files in one go for better performance.
++vendor/bin/phpstan analyze --no-progress --configuration="$TOP_LEVEL/core/phpstan.neon.dist" $ABS_FILES
++if [ "$?" -ne "0" ]; then
++  # If there are failures set the status to a number other than 0.
++  FINAL_STATUS=1
++  printf "\nPHPStan: ${red}failed${reset}\n"
++else
++  printf "\nPHPStan: ${green}passed${reset}\n"
++fi
++cd "$TOP_LEVEL"
 +
-   ############################################################################
-   ### JAVASCRIPT FILES
-   ############################################################################
++# Add a separator line to make the output easier to read.
++printf "\n"
++printf -- '-%.0s' {1..100}
++printf "\n"
++
+ # When the file core/phpcs.xml.dist has been changed, then PHPCS must check all files.
+ if [[ $PHPCS_XML_DIST_FILE_CHANGED == "1" ]]; then
+   # Test all files with phpcs rules.
 diff --git a/core/tests/Drupal/FunctionalTests/Bootstrap/ErrorContainer.php b/core/tests/Drupal/FunctionalTests/Bootstrap/ErrorContainer.php
 index 3cb81e0b29..17cf4b3efc 100644
 --- a/core/tests/Drupal/FunctionalTests/Bootstrap/ErrorContainer.php
